name: oselab-dev
channels:
  - conda-forge
dependencies:
  - python>=3.12, <3.13
  - flask>=1.1.2
  - Pygments>=2.2.0
  - pip
  - pip:
    - gunicorn
    - Flask-Assets
    - Flask-Markdown
    - pytest
